// TODO: consider renaming to match telegram's event names
export default {
	Raw: 'raw',
	ClientReady: 'ready',
	Message: 'message',
	MessageEdit: 'messageEdit',
	ChannelPost: 'channelPost',
	ChannelPostEdit: 'channelPostEdit',
	BusinessConnection: 'businessConnection',
	BusinessMessage: 'businessMessage',
	BusinessMessageEdit: 'businessMessageEdit',
	BusinessMessagesDelete: 'BusinessMessagesDelete',
	MessageReaction: 'messageReaction',
	MessageReactionCount: 'messageReactionCount',
	InlineQuery: 'inlineQuery',
	ChosenInlineResult: 'chosenInlineResult',
	CallbackQuery: 'callbackQuery',
	ShippingQuery: 'shippingQuery',
	PreCheckoutQuery: 'preCheckoutQuery',
	Poll: 'poll',
	PollAnswer: 'pollAnswer',
	ChatMeUpdate: 'chatMeUpdate',
	ChatMemberUpdate: 'chatMemberUpdate',
	ChatJoinRequest: 'chatJoinRequest',
	ChatBoost: 'chatBoost',
	ChatBoostRemove: 'chatBoostRemove'
}